---
- name: Example Playbook
  hosts: all
  vars:
    postgresql_config: true
    postgresql_enable_replication: true
    postgresql_listen_addresses:
      - "*"
    postgresql_replication:
      interface: enp0s8
      master: "{{ groups[postgresql_replication_group][0] }}"
      user: repluser
    postgresql_replication_group: postgres_replication
    pri_domain_name: test.vagrant.local
  tasks:
    - name: Include ansible-postgresql
      include_role:
        name: ansible-postgresql
