---
# tasks file for ansible-postgresql
- import_tasks: preflight.yml

- include_tasks: set_facts.yml

- include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- include_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- include_tasks: python.yml

- include_tasks: dbs.yml

- include_tasks: users.yml

- include_tasks: config.yml
  when: postgresql_config

- include_tasks: replication.yml
  when:
    - postgresql_config
    - postgresql_enable_replication
